import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Contrail_One } from "next/font/google";
import { getServerSession } from "next-auth";

import type { Metadata } from "next";

import { authOptions } from "@/app/api/auth/[...nextauth]/auth";
import StyledComponentsRegistry from "@/libs/styled-components";
import SessionProvider from "@/providers/session";
import ThemeProvider from "@/providers/theme";

import "@/app/globals.css";

const font = Contrail_One({
  weight: "400",
  variable: "--contrail-one",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={font.variable}>
        <StyledComponentsRegistry>
          <AntdRegistry>
            <SessionProvider session={session}>
              <ThemeProvider>{children}</ThemeProvider>
            </SessionProvider>
          </AntdRegistry>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
